/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aaaa;

import java.sql.*;
import javax.swing.*;
import co.yogesh.Captcha;

public class loginpage extends javax.swing.JFrame {

    /**
     * Creates new form loginpage
     */
    Captcha cap = new Captcha();
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    public loginpage() {
        initComponents();
        con = db.mycon();
        this.setLocationRelativeTo(null);
        cap.setImageCaptcha(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pasword = new javax.swing.JTextField();
        user_name = new javax.swing.JTextField();
        loginb = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        img = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Pasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 250, 39));

        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        jPanel1.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 250, 39));

        loginb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginb.setIcon(new javax.swing.ImageIcon("D:\\java project images\\login.png")); // NOI18N
        loginb.setText("Login");
        loginb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbActionPerformed(evt);
            }
        });
        jPanel1.add(loginb, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "patient", "doctor", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, -1, -1));

        img.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        img.setText("image");
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 155, 63));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 250, 39));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Verify");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 61, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\java project images\\Close.png")); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 68, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("New Patient Registeration ");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\java project images\\coronavirus-doctor.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, 0, 1220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginbActionPerformed
        String uname = user_name.getText();
        String pswd = Pasword.getText();
        JOptionPane.showMessageDialog(null, "your Username is " + uname + "   ");
        try {
            String sql = "SELECT * FROM login WHERE un=? AND paswd=?";
            pst = con.prepareCall(sql);
            pst.setString(1, uname);
            pst.setString(2, pswd);
            rs = pst.executeQuery();

            if (cap.Validate(img, jTextField1.getText())) {
                JOptionPane.showMessageDialog(this, "Captcha matched");

                if (rs.next()) {
                    JOptionPane.showMessageDialog(rootPane, "Your Login is successfull........." + uname);
                    admin A = new admin();
                    userpanel B = new userpanel();
                    doctorpanel C = new doctorpanel();
                    String userType = jComboBox1.getSelectedItem().toString();
                    if (userType.equals("admin")) {
                        A.setVisible(true);
                        A.setLocationRelativeTo(null);
                    } else if (userType.equals("patient")) {
                        new userpanel().setVisible(true);
                        B.setLocationRelativeTo(null);
                    }else if (userType.equals("doctor")) {
                        new doctorpanel().setVisible(true);
                        C.setLocationRelativeTo(null);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Your Login Failed");
                }
            } else
                JOptionPane.showMessageDialog(this, "Captcha does not match");

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    // TODO add your handling code here:
    // GEN-LAST:event_loginbActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel2MouseClicked
        if (cap.Validate(img, jTextField1.getText()))

            JOptionPane.showMessageDialog(this, "Captcha matched");

        else

            JOptionPane.showMessageDialog(this, "Captcha does not match");

    }// GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do You Really want to close Application", "Select",
                JOptionPane.YES_NO_OPTION);
        if (a == 0)
            System.exit(0);
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        registrationform A = new registrationform();
        A.setVisible(true);
        A.setLocationRelativeTo(null);

    }// GEN-LAST:event_jLabel4MouseClicked

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_user_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pasword;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loginb;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
